import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Head from "next/head";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
import FormPopup from "@/components/layout/FormPopup";

const satoshiRegular = localFont({
  src: "./fonts/Satoshi-Regular.otf",
  variable: "--font-satoshi-regular",
});

const satoshiMedium = localFont({
  src: "./fonts/Satoshi-Medium.otf",
  variable: "--font-satoshi-medium",
});

const hoperBegin = localFont({
  src: "./fonts/hoperbegin.otf",
  variable: "--font-hoper",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link
          href="https://fonts.cdnfonts.com/css/hoper-begin"
          rel="stylesheet"
        />
        <link
          href="https://fonts.cdnfonts.com/css/futura-std-4"
          rel="stylesheet"
        />
      </Head>
      <body
        className={`${satoshiRegular.variable} ${satoshiMedium.variable} ${hoperBegin.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
        <FormPopup />
      </body>
    </html>
  );
}
